---

application:
    call: 'interface-query'
    name: 'Interface Query'
    desc: >-
        Retrieves the specified ethernet or wireless interface device metrics, parsed the raw data, and ultimately
        outputs a human- or machine-readable representation of the specifically requested data points per the CLI
        options that were passed to this application.

    version:
        major: 0
        minor: 1
        patch: 0
        extra: ~
        named: 'partially-purged-appendage'

    author:
        name: 'Rob Frawley 2nd'
        mail: 'rmf@src.run'
        link: 'src.run/rmf'

    license:
        name: 'MIT License'
        link: 'src-run.mit-license.org'

    commands:

      wireless:
        load: true
        call: 'iq:wlan'
        name: 'Wireless'
        desc: >-
          Retrieves the specified wireless interface(s) device metrics and outputs a human- or machine-readable
          representation of the specifically requested data, per the CLI options that were passed to this command.

        interface:
          category: 'wireless'
          validate:
            name_matches_type: '^(wlp[a-z0-9]+|wlan[a-z0-9]+)$'

      ethernet:
        load: false
        call: 'iq:elan'
        name: 'Ethernet'
        desc: >-
          Retrieves the specified ethernet interface(s) device metrics and outputs a human- or machine-readable
          representation of the specifically requested data, per the CLI options that were passed to this command.

        interface:
          category: 'ethernet'
          validate:
            name_matches_type: '^(enp[a-z0-9]+|eth[a-z0-9]+)$'

      wwan:
        load: false
        call: 'iq:wwan'
        name: 'Wireless WAN'
        desc: >-
          Retrieves the specified wireless WAN interface(s) device metrics and outputs a human- or machine-readable
          representation of the specifically requested data, per the CLI options that were passed to this command.

        interface:
          category: 'ethernet'
          validate:
            name_matches_type: '^(wwp[a-z0-9]+)$'

      list:
        load: true
        call: 'iq:list'
        name: 'List'
        desc: >-
          Searches the local host system for recognized network interface(s), either wireless devices, wireless
          wide area network (WWAN) devices, ethernet devices, or both, and outputs the listing using either a
          human- or machine-readable representation, per the CLI options that were passed to this command.

        interface:
          category: 'listing'
          validate:
            name_matches_type: '^(wlp[a-z0-9]+|wlan[a-z0-9]+|enp[a-z0-9]+|eth[a-z0-9]+|wwp[a-z0-9]+)$'

...
