application:
  call: 'interface-query'
  name: 'Interface Query'
  desc: 'Retrieve requested data values for the specified wireless interfaces.'
  version:
    major: 0
    minor: 1
    patch: 0
    extra: null
  commands:
    wireless:
      name: 'wireless'
      desc: 'Retrieve requested data values for the specified wireless interfaces'
      interface:
        type: 'wireless'
        find: 'wl'
